version: 2
jobs:
  build-test-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run: make
      - run: make -C ./unit-tests all
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp libldclientapi.a /tmp/artifacts/linux-gcc-64bit-libldclientapi.a
              cp libldclientapi.so /tmp/artifacts/linux-gcc-64bit-libldclientapi.so
              cp libldclientapiplus.so /tmp/artifacts/linux-gcc-64bit-libldclientapiplus.so
      - store_artifacts:
          path: /tmp/artifacts

  build-test-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: make
      - run: make -C ./unit-tests all
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp libldclientapi.a /tmp/artifacts/osx-clang-64bit-libldclientapi.a
              cp libldclientapi.so /tmp/artifacts/osx-clang-64bit-libldclientapi.so
              cp libldclientapiplus.so /tmp/artifacts/osx-clang-64bit-libldclientapiplus.so
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux
      - build-test-osx
