version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux
      - build-test-osx
      - build-test-windows

jobs:
  build-test-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Build
          command: ./.ldrelease/build.sh
      - run:
          name: Test
          command: ./.ldrelease/test.sh
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp libldclientapi.a /tmp/artifacts/linux-gcc-64bit-libldclientapi.a
              cp libldclientapi.so /tmp/artifacts/linux-gcc-64bit-libldclientapi.so
              cp libldclientapiplus.so /tmp/artifacts/linux-gcc-64bit-libldclientapiplus.so
      - store_artifacts:
          path: /tmp/artifacts

  build-test-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Build
          command: ./.ldrelease/build.sh
      - run:
          name: Test
          command: ./.ldrelease/test.sh
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp libldclientapi.a /tmp/artifacts/osx-clang-64bit-libldclientapi.a
              cp libldclientapi.so /tmp/artifacts/osx-clang-64bit-libldclientapi.so
              cp libldclientapiplus.so /tmp/artifacts/osx-clang-64bit-libldclientapiplus.so
      - store_artifacts:
          path: /tmp/artifacts

  build-test-windows:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Build
          command: ./.ldrelease/build.ps1
      - run:
          name: Test
          command: ./.ldrelease/test.ps1
